apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: eece-system
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      containers:
      - name: backend
        image: {{DOCKERHUB_USERNAME}}/eece798n-backend:{{IMAGE_TAG}}
        env:
        - name: CV_EXTRACTION_URL
          value: "http://cv-format.eece-system.svc.cluster.local:3001"
        - name: JOB_DESCRIPTION_URL
          value: "http://job-description.eece-system.svc.cluster.local:3002"
        - name: CV_JOB_MATCHING_URL
          value: "http://cv-job-matching.eece-system.svc.cluster.local:3003"
        - name: INTERVIEW_QUESTIONS_URL
          value: "http://interview-questions.eece-system.svc.cluster.local:3004"
        - name: ANSWER_EVALUATION_URL
          value: "http://answer-evaluation.eece-system.svc.cluster.local:3005"
        - name: DB_HOST
          value: mysql-service  # Matches the MySQL service name
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: eece798
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: db-user

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: db-password
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "70m"  # Reduced from 500m
            memory: "128Mi"
          limits:
            cpu: "90m"  # Reduced from 1000m
            memory: "150Mi"
      
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: eece-system
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000