services:
  db:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobmatch
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  flask:
    build: ./backend
    container_name: jobmatch-backend
    ports:
      - "5003:5003"  # Expose Flask app port
    depends_on:
      - db            # Ensure db starts before Flask app

volumes:
  pgdata: