version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: eece798
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - eece-network

  backend:
    build: ./backend
    container_name: flask-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - eece-network

  frontend:
    build: ./frontend
    container_name: frontend-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - eece-network

networks:
  eece-network:
    driver: bridge
