version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: eece798
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - eece-network

  backend:
    build: ./backend
    container_name: flask-backend
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=eece798
      - DB_USER=root
      - DB_PASSWORD=password
    networks:
      - eece-network

  frontend:
    build: ./frontend
    container_name: flask-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - CV_EXTRACTION_URL=http://cv-extraction-api:3001 
      - JOB_DESCRIPTION_URL=http://job-description-api:3002 
    networks:
      - eece-network

  cv-extraction-api:
      stdin_open: true
      tty: true
      build:
        context: ./CV-Format
        dockerfile: Dockerfile
      command: python cv_format.py
      ports:
        - "3001:3001"
      networks:
        - eece-network  
      environment:
        - PORT=3001
  job-description-api:
        stdin_open: true
        tty: true
        build:
          context: ./job-description
          dockerfile: Dockerfile
        command: python job.py
        ports:
          - "3002:3002"
        networks:
          - eece-network  
        environment:
          - PORT=3002
networks:
  eece-network:
    driver: bridge
