services:
  db:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobmatch
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  flask:
    build: ./backend
    container_name: jobmatch-backend
    ports:
      - "5003:5003"
    environment:
      - TRANSFORMERS_CACHE=/app/model_cache  # Set cache location
    volumes:
      - model_cache:/app/model_cache  # Persistent model storage
    depends_on:
      - db

volumes:
  pgdata:
  model_cache:  # Add model cache volume