version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: eece798
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - eece-network

  backend:
    build: ./backend
    container_name: flask-backend
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=eece798
      - DB_USER=root
      - DB_PASSWORD=password
    networks:
      - eece-network

  frontend:
    build: ./frontend
    container_name: flask-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - eece-network

networks:
  eece-network:
    driver: bridge
