global:
  scrape_interval: 15s  # Scrape every 15 seconds

scrape_configs:
  # Scrape the backend Flask service for Prometheus metrics
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:5000']

  # Scrape CV Extraction API for Prometheus metrics
  - job_name: 'cv-extraction-api'
    static_configs:
      - targets: ['cv-extraction-api:3001']

  # Scrape Job Description API for Prometheus metrics
  - job_name: 'job-description-api'
    static_configs:
      - targets: ['job-description-api:3002']

  # Scrape CV Job Matching API for Prometheus metrics
  - job_name: 'cv-job-matching-api'
    static_configs:
      - targets: ['cv-job-matching-api:3003']

  # Scrape the Frontend (if you expose metrics here too)
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
