apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview-questions
  namespace: eece-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interview-questions
  template:
    metadata:
      labels:
        app: interview-questions
    spec:
      containers:
      - name: interview-questions
        image: {{DOCKERHUB_USERNAME}}/eece798n-interview-questions:{{IMAGE_TAG}}
        env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: HF_TOKEN
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: OPENAI_API_KEY
        - name: MISTRAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: MISTRAL_API_KEY
        ports:
        - containerPort: 3004
---
apiVersion: v1
kind: Service
metadata:
  name: interview-questions
  namespace: eece-system
spec:
  selector:
    app: interview-questions
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004