name: Deploy EECE798N Project

on:
  push:
    branches: [ "main" ]
    paths:
      - '**'  # Monitor all directories
  workflow_dispatch:

env:
  DOCKERHUB_REPO_PREFIX: ${{ secrets.DOCKERHUB_USERNAME }}/eece798n
  PROJECT_DIR: .

jobs:
  build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [
          'Interview-Questions',
          'CV-Format',
          'Evaluate-Answers',
          'backend',
          'cv-job-matching',
          'frontend',
          'job-description'
        ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & Push ${{ matrix.service }}
      run: |
        cd ${{ matrix.service }}
        docker build -t ${{ env.DOCKERHUB_REPO_PREFIX }}-$(echo "${{ matrix.service }}" | tr ' ' '-' | tr '[:upper:]' '[:lower:]'):${{ github.sha }} .
        docker push ${{ env.DOCKERHUB_REPO_PREFIX }}-$(echo "${{ matrix.service }}" | tr ' ' '-' | tr '[:upper:]' '[:lower:]'):${{ github.sha }}

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-federated-identity: true

    - name: Get AKS credentials
      run: |
        az aks get-credentials \
          --name Test \
          --resource-group Test_Group \
          --overwrite-existing

    
    - name: Create API Key Secrets
      run: |
        kubectl create secret generic api-keys \
          --namespace=eece-system \
          --from-literal=HF_TOKEN=${{ secrets.HF_TOKEN }} \
          --from-literal=OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
          --from-literal=MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }} \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to AKS
      run: |
        # Create namespace
        kubectl apply -f k8s/namespace.yaml --wait

        # Deploy MySQL
        kubectl apply -f k8s/database/mysql.yaml --namespace=eece-system

        # Update and deploy backend
        for service in backend frontend cv-job-matching cv-format job-description interview-questions evaluate-answers; do
          # Replace image tags in manifests
          find k8s/$service -name '*.yaml' -exec sed -i \
            -e "s/{{DOCKERHUB_USERNAME}}/${{ secrets.DOCKERHUB_USERNAME }}/g" \
            -e "s/{{IMAGE_TAG}}/${{ github.sha }}/g" {} \;

          # Apply manifests
          kubectl apply -f k8s/$service/ --namespace=eece-system
        done

   
        # Configure ingress
        echo "Deploying Nginx Ingress Controller..."
        kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/cloud/deploy.yaml
        
        # Add diagnostic information
        echo "Checking ingress controller status:"
        kubectl get pods -n ingress-nginx -w &
        kubectl get svc -n ingress-nginx -w &
        
        # Increase timeout and add retries
        for i in {1..5}; do
          if kubectl wait --namespace ingress-nginx \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/component=controller \
            --timeout=120s; then
            break
          else
            echo "Retry $i/5: Waiting for ingress controller..."
            sleep 10
          fi
        done
        
        # Apply ingress rules
        kubectl apply -f k8s/networking/ingress.yaml --namespace=eece-system
        
        # Final verification
        echo "Ingress controller details:"
        kubectl get svc -n ingress-nginx
        kubectl get ingress -n eece-system

        # Verify deployments
        kubectl rollout status --namespace=eece-system deployment/backend --timeout=300s
        kubectl rollout status --namespace=eece-system deployment/frontend --timeout=300s
        kubectl get all --namespace=eece-system